### ISSUE TITLE
__fzfcmd not found

### ISSUE THREAD

**Issue by blastdan** [mbhynes/fzf-gcloud#10]
you need to install the fzf key bindings and fuzzy completions, as well as basic fzf or the __fzfcmd isnt installed.

# To install useful key bindings and fuzzy completion:
$(brew --prefix)/opt/fzf/install

**Comment by mbhynes** [comment]
Thanks for opening this! I'll add a link to the readme in the requirements section to https://github.com/junegunn/fzf & note to follow the instructions there
