### ISSUE TITLE
Error: no such table: GCLOUD_CMD_CACHE

### ISSUE THREAD

**Issue by jogardi** [mbhynes/fzf-gcloud#12]
when I just do ctrl-k and nothing else I get this error:

Error: no such table: GCLOUD_CMD_CACHE.

I tried it again in a new window and still got it.

**Comment by mbhynes** [comment]
Hi @jogardi thanks very much for reporting this! I'm very sorry to get back to you on it so late, I'm afraid I missed this issue.

If you are still trying to use this script, could you please lmk what's in the sqlite database it creates in the file `GCLOUD_CMD_CACHE_DB="$HOME/.fzf-gcloud-cmd_cache.db`? 

If you run `sqlite3` on that file to inspect its tables & contents, that would tell me more. If it wasn't created, then that might be part of it. If you delete that file, it should be automatically re-created and populated.

https://github.com/mbhynes/fzf-gcloud/blob/main/fzf-gcloud.plugin.zsh#L5

**Comment by aculich** [comment]
I got this same error on my Mac due to the homebrew installation being in a symlinked path, so my PR #14 fixes this issue, as well.
