### ISSUE TITLE
Could not find a valid gcloud docs folder at: '/usr/bin/gcloud'.

### ISSUE THREAD

**Issue by oasaph** [mbhynes/fzf-gcloud#13]
I couldn't set up the SQLite cache and kept getting `Could not find a valid gcloud docs folder at: '/usr/bin/gcloud'.` error. Looking a little bit I've found that the variable [`gcloud_docs_root`](https://github.com/mbhynes/fzf-gcloud/blob/c981292c34f1665d45c8ad5a94f395fa67c57a3b/fzf-gcloud.plugin.zsh#L47)  has been set to the wrong path. Google must have updated the path to `/usr/lib/google-cloud-sdk/lib/surface` recently, so hard setting it to this path did the trick.

**Comment by mbhynes** [comment]
Thanks very much for reporting this! I'll have to set up a safer way to find the docs root
