### ISSUE TITLE
Suggestion: use a key binding other than CTRL+P

### ISSUE THREAD

**Issue by farzadmf** [mbhynes/fzf-gcloud#3]
As you probably know, <kbd>CTRL, P</kbd> is a "known" keybinding in the shell (brings up the previous command).

I think it's better to default to another keybinding. A keybinding that comes to my mind is <kbd>CTRL, G</kbd> (`G` for `gcloud`)

I created a PR to change it to <kbd>CTRL, G</kbd> instead; let me know what you think

**Comment by mbhynes** [comment]
That's a good point! I typically use `vi`-like keybindings to edit cli input/command history, so I overlooked this. I'm searching for the default `bash` keybindings with `man bash` and it looks like `C-g` is taken for some other default. Also, in truth, I'm not a huge fan of g (find it a bit uncomfortable personally). But `CTRL-i` looks free,  and is somewhat mnemomic for *i*nformation.  How about this?

**Comment by mbhynes** [comment]
Patched to CTRL-I in https://github.com/mbhynes/fzf-gcloud/pull/5

**Comment by farzadmf** [comment]
Good point about a "free" keybinding :+1: 

TBH I think the _ideal_ way to do this would be to somehow expose a function and include instructions on how to use a keybinding to call that function.

It might be a bit "intrusive" to force a keybinding to the user, but of course it's up to you :slightly_smiling_face:

**Comment by mbhynes** [comment]
> TBH I think the ideal way to do this would be to somehow expose a function and include instructions on how to use a keybinding to call that function.

Absolutely. I'm actually surprised this was useful enough to warrant putting that in the v2 roadmap ... 😄
